repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
        -   id: trailing-whitespace
        -   id: check-merge-conflict
        -   id: check-yaml
        -   id: end-of-file-fixer
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.5
    hooks:
        -   id: ruff
            args: [ --fix, --show-fixes ]
            types: [python]
        -   id: ruff-format
            types: [python]
