model_name_or_path: meta-llama/Llama-2-7b-hf
model_revision: main
use_flash_attn: true
tokenizer_name: meta-llama/Llama-2-7b-hf
use_slow_tokenizer: true
dataset_mixer:
    allenai/tulu-3-sft-mixture: 1.0
preprocessing_num_workers: 128
per_device_train_batch_size: 1 # note, this is set up for 8 GPUs
gradient_accumulation_steps: 16 # effective batch size 128 for tulu 2
learning_rate: 5.0e-06 # best LR so far
max_seq_length: 4096 # Note, reduced from 8192 to fit on one GPU with DeepSpeed Stage3
lr_scheduler_type: linear
warmup_ratio: 0.03
weight_decay: 0.0
num_train_epochs: 2
output_dir: output/tulu2_7b/
with_tracking: true
report_to:
  - wandb
logging_steps: 1000
checkpointing_steps: epoch
dataset_mix_dir: output/tulu2_7b